namespace SamsungNotes.UI.Controls
{
    enum KeyboardShortcutHelperCategory
    {
        General,
        NoteEditShortcut,
        TextEditShortcut,
        ViewControlShortcut,
        PanelControlShortcut
    };

    runtimeclass KeyboardShortcut
    {
        KeyboardShortcut(
            String funcName,
            String shortcutKey1,
            String shortcutKey2,
            String shortcutKey3,
            String shortcutKey4);
        String FuncName{ get; };
        String ShortcutKey1{ get; };
        String ShortcutKey2{ get; };
        String ShortcutKey3{ get; };
        String ShortcutKey4{ get; };
        KeyboardShortcutHelperCategory HelperCategory;
    };

    [default_interface]
    runtimeclass GroupInfosList
    {
        GroupInfosList();
        String Key;
        Windows.Foundation.Collections.IVector<KeyboardShortcut> Items{ get; };

        void Add(KeyboardShortcut item);
        void RemoveAt(UInt32 index);
        void Clear();
        UInt32 Size();

    };
}